testMode: true
batchProcess:
  eventCount: 10
  maxDuration: 10
  durable: false
rabbitmq:
  server:
    host: '13.125.235.249'
    port: '5672'
    id: 'username'
  queueName: 'testqueue'
  useReplyQueueFromMessage: true
  replyQueueName: 'replyQueue'
haproxy:
  reloadSecondNode: false
  master:
    host: '3.37.120.95'
    port: '5555'
    id: 'admin'
  second:
    host: '3.37.120.95'
    port: '5555'
    id: 'admin'